# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: 'CI'
on:
  workflow_dispatch: 
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'          
  release:
    types:
      - published

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace}}/nuget

defaults:
  run:
    shell: pwsh

jobs:
  create_nuget:
    runs-on: ubuntu-latest
    steps:   
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Get all history to allow automatic versioning using MinVer

    # Install the .NET SDK indicated in the global.json file
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
         

    - name: Update release notes
      if: github.event_name == 'release' 
      env:
        RELEASE_NAME: ${{ github.event.release.name }}
        RELEASE_BODY: ${{ github.event.release.body }}
      run: |   
        $name = $env:RELEASE_NAME
        $body = $env:RELEASE_BODY
        if($body -or $name){
            $releaseNotes = "# Release ${{ github.event.release.tag_name }}" 
            if($name){
                $releaseNotes = $releaseNotes + " - "  + $name
            }
            if($body){
                $releaseNotes = $releaseNotes + "`r`n`r`n"  + $body
            }
            
            foreach($csProjFileName in (Get-ChildItem "${{ github.workspace }}" -Recurse -Include *.csproj)) {
                Write-Host "Found project file '$csProjFileName'"
                $csProjDoc = [xml](Get-Content $csProjFileName)
                $releaseNotesNode = $csProjDoc.SelectSingleNode("Project/PropertyGroup/PackageReleaseNotes")

                if($releaseNotesNode.InnerText -clike "RELEASE_NOTES_PLACEHOLDER*") 
                {
                    Write-Host "`tPATCHING '$csProjFileName' with new release notes"
                    $releaseNotesNode.InnerText = "$releaseNotes"
                    $csProjDoc.Save($csProjFileName)
                }
            }
        }    

    # Create the NuGet package in the folder from the environment variable NuGetDirectory
    - run: dotnet pack --configuration Release --output ${{ env.NuGetDirectory }}
        
    - uses: actions/upload-artifact@v3
      with:
        name: nuget
        if-no-files-found: error
        retention-days: 7
        path: ${{ env.NuGetDirectory }}/*.nupkg
  
  deploy:    
    if: github.event_name == 'release' || (github.event_name == 'push' && github.ref_name == 'main')
    runs-on: ubuntu-latest
    needs: [ create_nuget ]
    steps:            
      - uses: actions/download-artifact@v3
        with:
          name: nuget
          path: ${{ env.NuGetDirectory }}

      # Install the .NET SDK indicated in the global.json file
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
              
      - name: Publish NuGet package
        env:
            EVENT_NAME: ${{ github.event_name }}
        run: |          
          $key = ($env:EVENT_NAME -eq 'release') ? "${{ secrets.NUGET_API_KEY }}" : "${{ secrets.GH_PACKAGE_REGISTRY_API_KEY }}"
          $source = ($env:EVENT_NAME -eq 'release') ? "https://api.nuget.org/v3/index.json" : "https://nuget.pkg.github.com/MichalBrylka/index.json"

          foreach($file in (Get-ChildItem "${{ env.NuGetDirectory }}" -Recurse -Include *.nupkg)) {
              dotnet nuget push $file --api-key "$key" --source "$source" --skip-duplicate
          } 